name: Validate, format and plan main.tf

on: push

jobs:
  terraform-validate:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.0.5
      - name: Terraform fmt
        id: fmt
        run: terraform fmt
